version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  mongodb:
    image: "mongo:4.2"
    ports:
      - "27017:27017"
  rabbitmq:
    image: "rabbitmq:latest"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    healthcheck:
        test: [ "CMD", "nc", "-z", "localhost", "5672" ]
        interval: 30s
        timeout: 10s
        retries: 5
  worker:
    build: .
    hostname: worker
    entrypoint: celery
    command: -A app worker --loglevel=info
    user: nobody
    restart: on-failure
    depends_on:
      - rabbitmq

