version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  mongodb:
    image: "mongo:4.2"
    ports:
      - "27017:27017"